### ISSUE TITLE
Migrate from TravisCI to Github actions

### ISSUE THREAD

**Issue by dgzlopes** [dgzlopes/cloud-detect#3]
You can use the existing `.travis.yaml` as a reference. Also, the badge on the readme needs to be changed.

**Comment by Arsh25** [comment]
I am currently working on this. Python 3.4 is now EOL. Do you still intend to support it? Currently, Python 3.4 does not work since PyYAML does not support it. This is a dependency inherited from Tox. Current progress can be tracked in my [fork](https://github.com/Arsh25/cloud-detect/actions)

**Comment by dgzlopes** [comment]
Thanks a lot for working on this!

It's OK to stop supporting Python 3.4 from my pov. Also, maybe we should test/add some newer Python versions.

**Comment by Arsh25** [comment]
I can add more. There is a weird error with Python 3.5 not being able to find the `README.md` in `setup.py`, This may need to be tracked in another issue but I pushed a [temporary fix](https://github.com/Arsh25/cloud-detect/commit/9d74fb90683fd6e3627daeff64b94ad0dae83161) on my fork. Let me know if this is ok for now otherwise I will try and find an actual fix before opening a PR

**Comment by dgzlopes** [comment]
We can skip 3.5 too if needed. I don't know of anyone running this with Python<3.6.

So, if it's an issue, we can remove it :)

**Comment by Arsh25** [comment]
eh, I worked around it
